In [1]:
using LinearAlgebra
using Random
rng = MersenneTwister()
Random.seed!(rng, 2018)
;

In [2]:
# Size of the matrix
n = 4;

# Random initialization of matrix A
G = zeros(Float64,n,n)
for i=1:n
    G[i,i] = rand(rng, 1:2)
    G[i+1:n,i] = rand(rng, -2:2, n-i)
end
A = G * transpose(G)
A0 = copy(A);


In [7]:
G

4×4 Matrix{Float64}:
  1.0  0.0  0.0  0.0
 -1.0  2.0  0.0  0.0
  1.0  2.0  1.0  0.0
  1.0  2.0  2.0  2.0

In [8]:
A

4×4 Matrix{Float64}:
  1.0  -1.0  1.0   1.0
 -1.0   5.0  3.0   3.0
  1.0   3.0  6.0   7.0
  1.0   3.0  7.0  13.0

In [5]:
b = rand(rng,4)

4-element Vector{Float64}:
 0.7750643105785386
 0.14209853614470824
 0.9846926453465281
 0.6384303868587522

In [6]:
function potrf!(A)
    n = size(A,1)
    for j=1:n
        for k=1:j-1, i=j:n
            A[i,j] -= A[i,k] * A[j,k]
        end
        ajj = sqrt(A[j,j])
        for i=j:n
            A[i,j] /= ajj
        end
    end
end

function potrs(A,b)
    n = length(b)
    x = copy(b)
    # Solve using matrix G
    for j = 1:n
        x[j] /= A[j,j]
        for i = j+1:n
            x[i] -= A[i,j] * x[j]
        end
    end
    # Solve using matrix G^T
    for i = n:-1:1
        for j = i+1:n
            x[i] -= A[j,i] * x[j]
        end
        x[i] /= A[i,i]
    end
    return x
end


potrs (generic function with 1 method)

In [7]:
potrs(A,b)

4-element Vector{Float64}:
  0.8264349059476096
  0.04219304443148277
 -0.00746462768545729
 -0.0017129232521308645